plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.5'
	id 'io.spring.dependency-management' version '1.1.6'
}

group = 'dev.cloud_computing_project'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(23)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'com.theokanning.openai-gpt3-java:service:0.18.2'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-web'
  	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'com.azure:azure-core:1.54.1'
  	implementation 'com.azure:azure-ai-textanalytics:5.5.3'
  	implementation 'com.microsoft.bot:bot-integration-spring:4.14.3'
	implementation 'com.microsoft.bot:bot-schema:4.14.3'
  	runtimeOnly 'org.postgresql:postgresql'
  	compileOnly 'org.projectlombok:lombok'
  	developmentOnly 'org.springframework.boot:spring-boot-devtools'
  	developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
  	annotationProcessor 'org.projectlombok:lombok'
  	testImplementation 'org.springframework.boot:spring-boot-starter-test'
  	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
