spring.application.name=cloudcomputingbackend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://88.99.68.132:5432/cloud_computing_project
spring.datasource.username=user
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update

# Azure Cognitive Services Configuration
azure.textanalytics.endpoint=https://cloudcomputingprojectclu.cognitiveservices.azure.com/
azure.textanalytics.key=7ealuM7HzWqrGjnytnP9WkcvCCCL9Cvofto9J9v1nckYf881KPmhJQQJ99AKACI8hq2XJ3w3AAAaACOGMcoV
azure.clu.endpoint=https://cloudcomputingprojectclu.cognitiveservices.azure.com/
azure.clu.key=7ealuM7HzWqrGjnytnP9WkcvCCCL9Cvofto9J9v1nckYf881KPmhJQQJ99AKACI8hq2XJ3w3AAAaACOGMcoV
azure.clu.project-name=cloudcomputingprojectclu
azure.clu.deployment-name=CloudComputingPorjectCLU


# GitHub OAuth2 Configuration
spring.security.oauth2.client.registration.github.client-id=Ov23linLe4gtqhs6n51B
spring.security.oauth2.client.registration.github.client-secret=2d00a5a430322da3b0bd91391c726842ff9fd9de
spring.security.oauth2.client.registration.github.scope=user:email

jwt.secret=myVerySecureSecretKey12345!@#
jwt.expiration=3600000


