spring.application.name=cloudcomputingbackend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_computing_project
spring.datasource.username=user
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update

# Azure Cognitive Services Configuration
azure.textanalytics.endpoint=https://<your-text-analytics-resource>.cognitiveservices.azure.com/
azure.textanalytics.key=<your-key>