spring.application.name=cloudcomputingbackend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_computing_project
spring.datasource.username=user
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update

# Azure Cognitive Services Configuration
azure.textanalytics.endpoint=https://<your-text-analytics-resource>.cognitiveservices.azure.com/
azure.textanalytics.key=<your-key>

# GitHub OAuth2 Configuration
spring.security.oauth2.client.registration.github.client-id=Ov23linLe4gtqhs6n51B
spring.security.oauth2.client.registration.github.client-secret=2d00a5a430322da3b0bd91391c726842ff9fd9de
spring.security.oauth2.client.registration.github.scope=user:email
